apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dyndeploys.dyndeploy.travix.com
spec:
  group: dyndeploy.travix.com
  names:
    kind: DynDeploy
    plural: dyndeploys
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              pattern: .+(:.+)?
              type: string
            keys:
              items:
                type: string
              type: array
            replicas:
              format: int32
              type: integer
          type: object
        status:
          properties:
            healthyReplicas:
              format: int32
              type: integer
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
